### ISSUE TITLE
Integrate Project Layout

### ISSUE THREAD

**Issue by cereallarceny** [4mber/OM-Welcome-Package#1]
https://app.lucidchart.com/invitations/accept/1158eee8-a446-4d30-906b-60abb6d993fc

**Comment by 4mber** [comment]
Yep, this is on the list of To Dos at the bottom of the Readme (which was more relevant when it was just me working on the project - of course all of the To Dos would work better as Issues).

**Comment by 4mber** [comment]
Create graphic thumbnails for projects from Patrick's lucidchart and insert on main readme
